name: Desk360LiveChat
options:
  developmentLanguage: en
  xcodeVersion: 12.4.0
  usesTabs: true
  tabWidth: 4
  indentWidth: 4
  deploymentTarget:
    iOS: 11.0

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.desk360.liveChat
    SWIFT_VERSION: 5.0

targets:
  Desk360LiveChat:
    type: framework
    platform: iOS
    deploymentTarget: 11.0
    sources: [Sources]
    settings:
      INFOPLIST_FILE: Configs/Desk360LiveChat.plist
    postbuildScripts:
      - script: swiftlint
        name: SwiftLint
  Example:
    type: application
    platform: iOS
    sources: [Example]
    deploymentTarget: 11.0
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.desk360.liveChat.example
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    dependencies:
      - target: Desk360LiveChat
    postbuildScripts:
      - script: swiftlint
        name: SwiflLint
  Tests:
    type: bundle.unit-test
    platform: iOS 
    scheme: {}
    sources: [Tests]
    dependencies:
     - target: Desk360LiveChat
